export function currencyForCountry(country: string) {
  const c = country.toUpperCase();
  if (
    "AT BE CY DE EE ES FI FR GR HR IE IT LT LU LV MT NL PT SI SK BG"
      .split(" ")
      .includes(c)
  )
    return "EUR";
  const map: Record<string, string> = {
    GB: "GBP",
    US: "USD",
    CA: "CAD",
    AU: "AUD",
    NZ: "NZD",
    JP: "JPY",
    CN: "CNY",
    IN: "INR",
    CH: "CHF",
    LI: "CHF",
    BR: "BRL",
    MX: "MXN",
    KR: "KRW",
    SG: "SGD",
    HK: "HKD",
    TW: "TWD",
    ZA: "ZAR",
    AE: "AED",
    SA: "SAR",
    QA: "QAR",
    KW: "KWD",
    BH: "BHD",
    OM: "OMR",
    IL: "ILS",
    TR: "TRY",
    PL: "PLN",
    CZ: "CZK",
    DK: "DKK",
    SE: "SEK",
    NO: "NOK",
    IS: "ISK",
    HU: "HUF",
    RO: "RON",
    UA: "UAH",
    RS: "RSD",
    TH: "THB",
    MY: "MYR",
    ID: "IDR",
    PH: "PHP",
    VN: "VND",
    PK: "PKR",
    BD: "BDT",
    LK: "LKR",
    NP: "NPR",
    EG: "EGP",
    MA: "MAD",
    NG: "NGN",
    KE: "KES",
    GH: "GHS",
    TZ: "TZS",
    UG: "UGX",
    AR: "ARS",
    CL: "CLP",
    CO: "COP",
    PE: "PEN",
    UY: "UYU",
    PY: "PYG",
    BO: "BOB",
    CR: "CRC",
    DO: "DOP",
    GT: "GTQ",
    HN: "HNL",
    NI: "NIO",
    JM: "JMD",
    TT: "TTD",
    BS: "BSD",
    BB: "BBD",
    EC: "USD",
    PA: "USD",
    SV: "USD",
    PR: "USD",
    KZ: "KZT",
    UZ: "UZS",
    GE: "GEL",
    AM: "AMD",
    AZ: "AZN",
    AL: "ALL",
    MK: "MKD",
    BA: "BAM",
    ME: "EUR",
    XK: "EUR",
    MC: "EUR",
    AD: "EUR",
    SM: "EUR",
    VA: "EUR",
    MU: "MUR",
    SC: "SCR",
    MV: "MVR",
    FJ: "FJD",
    PG: "PGK",
    KH: "KHR",
    LA: "LAK",
    MN: "MNT",
    JO: "JOD",
    LB: "LBP",
    IQ: "IQD",
    TN: "TND",
    DZ: "DZD",
    AO: "AOA",
    ZM: "ZMW",
    BW: "BWP",
    NA: "NAD",
    MZ: "MZN",
  };
  return map[c] || "GBP";
}
export function countryFromLocale(locale: string) {
  try {
    return new Intl.Locale(locale).maximize().region || "GB";
  } catch {
    return "GB";
  }
}
export function convertedPrice(
  pence: number,
  currency: string,
  rate: number,
  locale = "en-GB",
) {
  return new Intl.NumberFormat(locale, {
    style: "currency",
    currency,
    currencyDisplay: "symbol",
  }).format((pence / 100) * rate);
}
